export const en = {
  setSpeed: "Set speed cm/s",
  setDistance: "Set fly distance cm",
  setRotate: "Set rotate angle",
  toggleControls: "Hide/Show controls",
  connect: "Connect",
  disconnect: "Disonnect",
  download: "Download",
  delete: "Delete",
  screenshot: "Screenshot",
  cm: "cm",
  degrees: "degrees",
  emergencyStop: "Emergency stop",
  landDrone: "Land the drone",
  turnClockwise: "Turn clockwise on",
  turnCounterClockwise: "Turn counterсlockwise on",
  flyForward: "Fly forward on",
  flyBack: "Fly back on",
  flyTop: "Fly top on",
  flyLeft: "Fly left on",
  flyDown: "Fly down on",
  flyRight: "Fly right on",
  flyTime: "Fly time",
  height: "Height",
  connectWithDrone: "Connect with the drone",
  takeOffDrone: "Take off the drone",
  startVideoStream: "Start videostream",
  finishVideoStream: "Finish videostream",
  startDroneConnectInfo:
    "Click here or press Enter to start connection with drone",
  startVideoStreamInfo: "Click here or press V to start video stream",
};
