export const uk = {
  setSpeed: "Швидкість см/с",
  setDistance: "Дальність польоту см",
  setRotate: "Кут оберту",
  toggleControls: "Приховати/показати елементи керування",
  connect: "Зʼєднання",
  disconnect: "Зʼєднання відсутнє",
  download: "Скачати",
  screenshot: "Знімок",
  cm: "см",
  degrees: "градусів",
  emergencyStop: "Аварійна зупинка",
  landDrone: "Посадити дрон",
  turnClockwise: "Поверніть за годинниковою стрілкою",
  turnCounterClockwise: "Поверніть проти годинниковою стрілкою",
  flyForward: "Летіти вперед на",
  flyBack: "Летіти назад на",
  flyTop: "Летіти вверх на",
  flyLeft: "Летіти вліво на",
  flyDown: "Летіти вниз на",
  flyRight: "Летіти вправо на",
  connectWithDrone: "Підключіться до дрона",
  takeOffDrone: "Взлетіти",
  startVideoStream: "Почати відео трансляцію",
  finishVideoStream: "Закінчити відео трансляцію",
  startDroneConnectInfo:
    "Клацніть тут або натисніть Enter, щоб почати з’єднання з дроном",
  startVideoStreamInfo:
    "Клацніть тут або натисніть V, щоб почати відео трансляцію",
};
